[[custom_groups]]
name = "ç¯çƒç½‘ç»œ"
type = "url-test"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
rule = [".*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "Netflix"
type = "url-test"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "æ‹¦æˆªè¿æ¥"
type = "select"
rule = ["[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "Telegram"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "SpeedTest"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]
 
[[custom_groups]]
name = "AI"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "é¦™æ¸¯ä¸²æµéªŒè¯"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "EdgeWare"
type = "select"
rule = ["[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "[]âš¡ å‡è¡¡è´Ÿè½½", "[] Exé¦™æ¸¯", "[] ZHSé¦™æ¸¯", "[] Exå°æ¹¾", "[] ZHSå°æ¹¾", "[] Exæ˜Ÿå›½", "[] ZHSæ˜Ÿå›½", "[] Exæ—¥æœ¬", "[] ZHSæ—¥æœ¬", "[] Exç¾å›½", "[] ZHSç¾å›½", "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹", "[] å…¨éƒ¨èŠ‚ç‚¹", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "é¦™æ¸¯åŸç”Ÿ"
type = "url-test"
rule = ["HKT|ä¹é¾™|é“ ç”²|å¤©æœº|å¥‘çº¦|TVB"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "Exé¦™æ¸¯"
type = "url-test"
rule = ["^(?!.*(æ·±åœ³))(?=.*(?:é¦™æ¸¯)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "Exå°æ¹¾"
type = "url-test"
rule = ["(?=.*(å°æ¹¾)(?!.*(åŠ¨ç”»))).*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "Exæ˜Ÿå›½"
type = "url-test"
rule = ["^(?=.*(?:æ˜Ÿå›½)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHSé¦™æ¸¯"
type = "url-test"
rule = ["^(?!.*(æ·±åœ³))(?=.*(?:é¦™æ¸¯)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHSå°æ¹¾"
type = "url-test"
rule = ["(?=.*(å°æ¹¾)(?!.*(åŠ¨ç”»))).*"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHSæ˜Ÿå›½"
type = "url-test"
rule = ["^(?=.*(?:æ˜Ÿå›½)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHSæ—¥æœ¬"
type = "url-test"
rule = ["^(?=.*(?:æ—¥æœ¬)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[[custom_groups]]
name = "ZHSç¾å›½"
type = "url-test"
rule = ["^(?=.*(?:ç¾å›½)).*$"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true

[ruleset]
# Enable generating rules with rulesets
enabled = true

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/TVB-AD.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ‘¾ AI"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/AI.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸŒ ç¯çƒç½‘ç»œ"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/GlobalWebsiteAndForeignlMedia.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“º Netflix"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/Netflix.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“¨ Telegram"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ‡­ğŸ‡° é¦™æ¸¯ä¸²æµéªŒè¯"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/HK-Media.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ‡­ğŸ‡° EdgeWare"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/EdgeWare.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/Microsoft.list"
type = "surge-ruleset"
interval = 86400

[[rulesets]]
group = "ğŸ“ˆ SpeedTest"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/SpeedTest.list"
type = "surge-ruleset"
interval = 86400
