version = 1

[custom]
enable_rule_generator = true
overwrite_original_rules = true
add_emoji = true
remove_old_emoji = true

# è®¾ç½®åˆ†ç»„æ ‡å¿—ä½
[[custom_groups]]
name = "ğŸŒ ç¯çƒç½‘ç»œ"
type = "select"
rule = [
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ‡­ğŸ‡° Exé¦™æ¸¯",
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½",
    "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹",
    "[]DIRECT",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ YouTube"
type = "select"
rule = [
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ‡­ğŸ‡° Exé¦™æ¸¯",
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½",
    "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹",
    "[]DIRECT",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ“º Netflix"
type = "select"
rule = [
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ‡­ğŸ‡° Exé¦™æ¸¯",
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½",
    "[]ğŸŒ ç¯çƒç½‘ç»œ",
    "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹",
    "[]DIRECT",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
type = "select"
rule = [
    "[]DIRECT",
    "[]REJECT"
]

[[custom_groups]]
name = "ğŸ“¨ Telegram"
type = "select"
rule = [
    "[]ğŸŒ ç¯çƒç½‘ç»œ",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° Exé¦™æ¸¯",
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½"
]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = [
    "[]ğŸŒ ç¯çƒç½‘ç»œ",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° Exé¦™æ¸¯",
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½"
]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = [
    "[]ğŸŒ ç¯çƒç½‘ç»œ",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ‡­ğŸ‡° Exé¦™æ¸¯",
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½"
]

[[custom_groups]]
name = "ğŸ“ˆ SpeedTest"
type = "select"
rule = [
    "[]DIRECT",
    "[]ğŸŒ ç¯çƒç½‘ç»œ",
    "[]ğŸ“º Netflix",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ‘¾ AI"
type = "select"
rule = [
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹"
]

[[custom_groups]]
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 60
tolerance = 100
rule = [
    "[]ğŸ‡­ğŸ‡° Exé¦™æ¸¯",
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½",
    "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯ä¸²æµéªŒè¯"
type = "select"
rule = [
    "[]ğŸ‡­ğŸ‡° é¦™æ¸¯åŸç”Ÿ",
    "[]ğŸ‡­ğŸ‡° ZHSä¹é¾™",
    "[]ğŸ‡­ğŸ‡° ZHSé“ ç”²",
    "[]ğŸ‡­ğŸ‡° ZHSå¥‘çº¦",
    "[]ğŸ‡­ğŸ‡° TVB",
    "[]ğŸ‡­ğŸ‡° HKT",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° EdgeWare"
type = "select"
rule = [
    "[]DIRECT",
    "[]ğŸŒ ç¯çƒç½‘ç»œ",
    "[]âš¡ å…¨éƒ¨èŠ‚ç‚¹",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹",
    "[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©",
    "[]ğŸ‡­ğŸ‡° Exé¦™æ¸¯",
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ Exå°æ¹¾",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ Exç¾å›½",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½"
]

[[custom_groups]]
name = "ğŸ› Gov"
type = "select"
rule = [
    "[]ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯",
    "[]ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾",
    "[]ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½",
    "[]ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬",
    "[]ğŸ‡ºğŸ‡¸ ZHSç¾å›½",
    "[]ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹",
    "[]DIRECT"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯åŸç”Ÿ"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(HKT|ä¹é¾™|é“ ç”²|å¥‘çº¦|TVB)"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° Exé¦™æ¸¯"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "^(?!.*(æ·±åœ³))(?=.*(?:é¦™æ¸¯)).*$"
]

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ Exå°æ¹¾"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(?=.*(å°æ¹¾)(?!.*(åŠ¨ç”»))).*"
]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ Exæ˜Ÿå›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    ".*(?<!(æ›´))(æ–°åŠ å¡)(?!.*æ¸¸æˆ).*"
]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ Exç¾å›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(?=.*(ç¾å›½)(?!.*(æ¸¸æˆ))).*"
]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ Exæ—¥æœ¬"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(?=.*(æ—¥æœ¬)(?!.*(æ¸¸æˆ))).*"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° ZHSé¦™æ¸¯"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "^(?=.*(?:HK))(?!.*(?:é¦™æ¸¯|æ¸¸æˆ)).*$"
]

[[custom_groups]]
name = "ğŸ‡¹ğŸ‡¼ ZHSå°æ¹¾"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(?=.*(TW)(?!.*(æ¸¸æˆ))).*"
]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ZHSæ˜Ÿå›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(?=.*(SG)(?!.*(æ¸¸æˆ))).*"
]

[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ ZHSç¾å›½"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(?=.*(US)(?!.*(æ¸¸æˆ))).*"
]

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ ZHSæ—¥æœ¬"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(?=.*(JP)(?!.*(æ¸¸æˆ))).*"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° ZHSä¹é¾™"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(ä¹é¾™)"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° ZHSé“ ç”²"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(é“ ç”²)"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° ZHSå¥‘çº¦"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(å¥‘çº¦)"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° HKT"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(HKT)"
]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° TVB"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "(TVB)"
]

[[custom_groups]]
name = "âš¡ å…¨éƒ¨èŠ‚ç‚¹"
type = "url-test"
url = "http://www.gstatic.com/generate_204"
interval = 600
rule = [
    "^((?!ä¸­å›½|å›å›½|æ¸¸æˆ|é™é€Ÿ|ç»“ç®—|æµé‡).)*$"
]


[[custom_groups]]
name = "ğŸ“Œ å…¨éƒ¨èŠ‚ç‚¹"
type = "select"
rule = [".*"]

# è®¾ç½®è§„åˆ™æ ‡å¿—ä½
[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/Direct.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆªè¿æ¥"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/TVB-AD.list"

[[rulesets]]
group = "ğŸ YouTube"
ruleset = "https://raw.githubusercontent.com/tindy2013/subconverter/refs/heads/master/base/rules/ACL4SSR/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸ‘¾ AI"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/AI.list"

[[rulesets]]
group = "ğŸ“º Netflix"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/Netflix.list"

[[rulesets]]
group = "ğŸ“¨ Telegram"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"

[[rulesets]]
group = "ğŸ‡­ğŸ‡° é¦™æ¸¯ä¸²æµéªŒè¯"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/HK-Media.list"

[[rulesets]]
group = "ğŸ‡­ğŸ‡° EdgeWare"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/EdgeWare.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/Microsoft.list"

[[rulesets]]
group = "ğŸ“ˆ SpeedTest"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/SpeedTest.list"

[[rulesets]]
group = "ğŸ› Gov"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/gov.list"

[[rulesets]]
group = "ğŸŒ ç¯çƒç½‘ç»œ"
ruleset = "https://raw.githubusercontent.com/Doraemon2020/Policy/master/Rules/Extra.list"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŒ ç¯çƒç½‘ç»œ"
ruleset = "[]MATCH"
# è®¾ç½®è§„åˆ™æ ‡å¿—ä½

[[emoji]]
match = "(?i:Bandwidth|pire|æµé‡|æ—¶é—´|åº”æ€¥|è¿‡æœŸ)"
emoji = "ğŸ³ï¸â€ğŸŒˆ"

[[emoji]]
match = "(?i:\\bHK[G]?\\b|Hong.*?Kong|\\bHKT\\b|\\bHKBN\\b|\\bHGC\\b|\\bWTT\\b|\\bCMI\\b|[^-]æ¸¯)"
emoji = "ğŸ‡­ğŸ‡°"

[[emoji]]
match = "(?i:\\bTW[N]?\\b|Taiwan|æ–°åŒ—|å½°åŒ–|\\bCHT\\b|å°æ¹¾|[^-]å°|\\bHINET\\b)"
emoji = "ğŸ‡¹ğŸ‡¼"

[[emoji]]
match = "(?i:\\bSG[P]?\\b|Singapore|æ–°åŠ å¡|ç‹®åŸ|[^-]æ–°)"
emoji = "ğŸ‡¸ğŸ‡¬"

[[emoji]]
match = "(?i:\\bJP[N]?\\b|Japan|Tokyo|Osaka|Saitama|æ—¥æœ¬|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|[^-]æ—¥)"
emoji = "ğŸ‡¯ğŸ‡µ"

[[emoji]]
match = "(?i:\\bK[O]?R\\b|Korea|é¦–å°”|éŸ©|éŸ“)"
emoji = "ğŸ‡°ğŸ‡·"

[[emoji]]
match = "(?i:\\bUS[A]?\\b|America|United.*?States|ç¾å›½|[^-]ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥)"
emoji = "ğŸ‡ºğŸ‡¸"

[[emoji]]
match = "(Ascension|é˜¿æ£®æ¾)"
emoji = "ğŸ‡¦ğŸ‡¨"

[[emoji]]
match = "(?i:\\bUAE\\b|Dubai|é˜¿è”é…‹|è¿ªæ‹œ)"
emoji = "ğŸ‡¦ğŸ‡ª"

[[emoji]]
match = "(é˜¿å°”å·´å°¼äºš|Albania)"
emoji = "ğŸ‡¦ğŸ‡±"

[[emoji]]
match = "(Argentina|é˜¿æ ¹å»·)"
emoji = "ğŸ‡¦ğŸ‡·"

[[emoji]]
match = "(Austria|Vienna|å¥¥åœ°åˆ©|ç»´ä¹Ÿçº³)"
emoji = "ğŸ‡¦ğŸ‡¹"

[[emoji]]
match = "(?i:\\bAU[S]?\\b|Australia|Sydney|æ¾³å¤§åˆ©äºš|æ¾³æ´²|æ‚‰å°¼)"
emoji = "ğŸ‡¦ğŸ‡º"

[[emoji]]
match = "(é˜¿å¡æ‹œç–†|Azerbaijan)"
emoji = "ğŸ‡¦ğŸ‡¿"

[[emoji]]
match = "(æ³¢é»‘å…±å’Œå›½|æ³¢å£«å°¼äºšä¸èµ«å¡å“¥ç»´çº³|Bosnia|Herzegovina)"
emoji = "ğŸ‡§ğŸ‡¦"

[[emoji]]
match = "(Belgium|æ¯”åˆ©æ—¶)"
emoji = "ğŸ‡§ğŸ‡ª"

[[emoji]]
match = "(ä¿åŠ åˆ©äºš|Bulgaria)"
emoji = "ğŸ‡§ğŸ‡¬"

[[emoji]]
match = "(Brazil|Paulo|å·´è¥¿|åœ£ä¿ç½—)"
emoji = "ğŸ‡§ğŸ‡·"

[[emoji]]
match = "(?i:\\bCA[N]?\\b|Canada|Toronto|Montreal|Vancouver|åŠ æ‹¿å¤§|è’™ç‰¹åˆ©å°”|æ¸©å“¥å|æ¥“è‘‰|æ«å¶)"
emoji = "ğŸ‡¨ğŸ‡¦"

[[emoji]]
match = "(Switzerland|Zurich|ç‘å£«|è‹é»ä¸–)"
emoji = "ğŸ‡¨ğŸ‡­"

[[emoji]]
match = "(æ™ºåˆ©|Chile)"
emoji = "ğŸ‡¨ğŸ‡±"

[[emoji]]
match = "(Colombia|å“¥ä¼¦æ¯”äºš)"
emoji = "ğŸ‡¨ğŸ‡´"

[[emoji]]
match = "(Costa Rica|å“¥æ–¯è¾¾é»åŠ )"
emoji = "ğŸ‡¨ğŸ‡·"

[[emoji]]
match = "(å¡æµ¦è·¯æ–¯|Cyprus)"
emoji = "ğŸ‡¨ğŸ‡¾"

[[emoji]]
match = "(Czech|æ·å…‹)"
emoji = "ğŸ‡¨ğŸ‡¿"

[[emoji]]
match = "(?i:\\bDE[U]?\\b|Germany|æ³•å…°å…‹ç¦|å¾·(å›½|æ„å¿—)|ä¸­å¾·|^å¾·$)"
emoji = "ğŸ‡©ğŸ‡ª"

[[emoji]]
match = "(?i:\\bD[N]?K\\b|Denmark|ä¸¹éº¦)"
emoji = "ğŸ‡©ğŸ‡°"

[[emoji]]
match = "(çˆ±æ²™å°¼äºš|Estonia)"
emoji = "ğŸ‡ªğŸ‡ª"

[[emoji]]
match = "(åŸƒåŠ|Egypt)"
emoji = "ğŸ‡ªğŸ‡¬"

[[emoji]]
match = "(?i:\\bES[P]?\\b|Spain|è¥¿ç­ç‰™)"
emoji = "ğŸ‡ªğŸ‡¸"

[[emoji]]
match = "(Europe|æ¬§æ´²)"
emoji = "ğŸ‡ªğŸ‡º"

[[emoji]]
match = "(Finland|Helsinki|èŠ¬å…°|èµ«å°”è¾›åŸº)"
emoji = "ğŸ‡«ğŸ‡®"

[[emoji]]
match = "(?i:\\bFR[A]?\\b|France|Paris|æ³•å›½|å·´é»)"
emoji = "ğŸ‡«ğŸ‡·"

[[emoji]]
match = "(?i:\\bUK\\b|\\bGB[R]?\\b|England|United.*?Kingdom|London|è‹±å›½|[^-]è‹±|ä¼¦æ•¦)"
emoji = "ğŸ‡¬ğŸ‡§"

[[emoji]]
match = "(å¸Œè…Š|Greece)"
emoji = "ğŸ‡¬ğŸ‡·"

[[emoji]]
match = "(æ ¼é²å‰äºš|Georgia)"
emoji = "ğŸ‡¬ğŸ‡ª"

[[emoji]]
match = "(å…‹ç½—åœ°äºš|Croatia)"
emoji = "ğŸ‡­ğŸ‡·"

[[emoji]]
match = "(Hungary|åŒˆç‰™åˆ©)"
emoji = "ğŸ‡­ğŸ‡º"

[[emoji]]
match = "(Indonesia|Jakarta|å°å°¼|å°åº¦å°¼è¥¿äºš|é›…åŠ è¾¾)"
emoji = "ğŸ‡®ğŸ‡©"

[[emoji]]
match = "(Ireland|Dublin|çˆ±å°”å…°|éƒ½æŸæ—)"
emoji = "ğŸ‡®ğŸ‡ª"

[[emoji]]
match = "(Israel|ä»¥è‰²åˆ—)"
emoji = "ğŸ‡®ğŸ‡±"

[[emoji]]
match = "(é©¬æ©å²›|Mann)"
emoji = "ğŸ‡®ğŸ‡²"

[[emoji]]
match = "(?i:\\bIN[D]?\\b|India|Mumbai|å°åº¦|å­Ÿä¹°|åŠ å°”å„ç­”|è´¾åå¾·|æ³°ç±³å°”çº³å¾·)"
emoji = "ğŸ‡®ğŸ‡³"

[[emoji]]
match = "(ä¼Šæœ—|Iran)"
emoji = "ğŸ‡®ğŸ‡·"

[[emoji]]
match = "(?i:\\bIS[L]?\\b|Iceland|å†°å²›)"
emoji = "ğŸ‡®ğŸ‡¸"

[[emoji]]
match = "(Italy|Milan|æ„å¤§åˆ©|ç±³å…°)"
emoji = "ğŸ‡®ğŸ‡¹"

[[emoji]]
match = "(çº¦æ—¦|Jordan)"
emoji = "ğŸ‡¯ğŸ‡´"

[[emoji]]
match = "(è‚¯å°¼äºš|Kenya)"
emoji = "ğŸ‡°ğŸ‡ª"

[[emoji]]
match = "(å‰å°”å‰æ–¯æ–¯å¦|Kyrgyzstan)"
emoji = "ğŸ‡°ğŸ‡¬"

[[emoji]]
match = "(æŸ¬åŸ”å¯¨|Cambodia)"
emoji = "ğŸ‡°ğŸ‡­"

[[emoji]]
match = "(North.*?Korea|æœé²œ)"
emoji = "ğŸ‡°ğŸ‡µ"

[[emoji]]
match = "(å“ˆè¨å…‹æ–¯å¦|Kazakhstan)"
emoji = "ğŸ‡°ğŸ‡¿"

[[emoji]]
match = "(ç«‹é™¶å®›|Lietuvos)"
emoji = "ğŸ‡±ğŸ‡¹"

[[emoji]]
match = "(å¢æ£®å ¡|Luxemburg|Luxembourg)"
emoji = "ğŸ‡±ğŸ‡º"

[[emoji]]
match = "(æ‹‰è„±ç»´äºš|Latvia)"
emoji = "ğŸ‡±ğŸ‡»"

[[emoji]]
match = "(Moldova|æ‘©å°”å¤šç“¦)"
emoji = "ğŸ‡²ğŸ‡©"

[[emoji]]
match = "(åŒ—é©¬å…¶é¡¿|Macedonia)"
emoji = "ğŸ‡²ğŸ‡°"

[[emoji]]
match = "(è’™å¤|ĞœĞ¾Ğ½Ğ³Ğ¾Ğ»ÑƒĞ»Ñ|Mongolia)"
emoji = "ğŸ‡²ğŸ‡³"

[[emoji]]
match = "(Macao|æ¾³é—¨|\\bCTM\\b)"
emoji = "ğŸ‡²ğŸ‡´"

[[emoji]]
match = "(å¢¨è¥¿å“¥|Mico)"
emoji = "ğŸ‡²ğŸ‡½"

[[emoji]]
match = "(Malaysia|é©¬æ¥|MY)"
emoji = "ğŸ‡²ğŸ‡¾"

[[emoji]]
match = "(å°¼æ—¥åˆ©äºš|Nigeria)"
emoji = "ğŸ‡³ğŸ‡¬"

[[emoji]]
match = "(?i:\\bNL[D]?\\b|Netherlands|è·å…°|é˜¿å§†æ–¯ç‰¹ä¸¹)"
emoji = "ğŸ‡³ğŸ‡±"

[[emoji]]
match = "(æŒªå¨|Norway)"
emoji = "ğŸ‡³ğŸ‡´"

[[emoji]]
match = "(æ–°è¥¿å…°|çº½è¥¿å…°|New Zealand)"
emoji = "ğŸ‡³ğŸ‡¿"

[[emoji]]
match = "(Philippines|è²å¾‹å®¾)"
emoji = "ğŸ‡µğŸ‡­"

[[emoji]]
match = "(Pakistan|å·´åŸºæ–¯å¦)"
emoji = "ğŸ‡µğŸ‡°"

[[emoji]]
match = "(?i:\\bP[O]?L\\b|Poland|æ³¢å…°)"
emoji = "ğŸ‡µğŸ‡±"

[[emoji]]
match = "(å·´æ‹¿é©¬|Panama)"
emoji = "ğŸ‡µğŸ‡¦"

[[emoji]]
match = "(ç§˜é²|Peru)"
emoji = "ğŸ‡µğŸ‡ª"

[[emoji]]
match = "(è‘¡è„ç‰™|Portugal)"
emoji = "ğŸ‡µğŸ‡¹"

[[emoji]]
match = "(Romania|ç½—é©¬å°¼äºš)"
emoji = "ğŸ‡·ğŸ‡´"

[[emoji]]
match = "(å¡å°”ç»´äºš|Serbia)"
emoji = "ğŸ‡·ğŸ‡¸"

[[emoji]]
match = "(?i:\\bRU[S]?\\b|Russia|Moscow|Petersburg|Siberia|ä¼¯åŠ›|è«æ–¯ç§‘|åœ£å½¼å¾—å ¡|è¥¿ä¼¯åˆ©äºš|æ–°è¥¿ä¼¯åˆ©äºš|å“ˆå·´ç½—å¤«æ–¯å…‹|ä¿„ç½—æ–¯|[^-]ä¿„)"
emoji = "ğŸ‡·ğŸ‡º"

[[emoji]]
match = "(Arabia|æ²™ç‰¹)"
emoji = "ğŸ‡¸ğŸ‡¦"

[[emoji]]
match = "(Sweden|ç‘å…¸)"
emoji = "ğŸ‡¸ğŸ‡ª"

[[emoji]]
match = "(æ–¯æ´›æ–‡å°¼äºš|Slovenia)"
emoji = "ğŸ‡¸ğŸ‡®"

[[emoji]]
match = "(æ–¯æ´›ä¼å…‹|Slovensko)"
emoji = "ğŸ‡¸ğŸ‡°"

[[emoji]]
match = "(Thailand|æ³°å›½|æ›¼è°·)"
emoji = "ğŸ‡¹ğŸ‡­"

[[emoji]]
match = "(çªå°¼æ–¯|Tunisia)"
emoji = "ğŸ‡¹ğŸ‡³"

[[emoji]]
match = "(Turkey|TR|åœŸè€³å…¶|ä¼Šæ–¯å¦å¸ƒå°”)"
emoji = "ğŸ‡¹ğŸ‡·"

[[emoji]]
match = "(ä¹Œæ‹‰åœ­|Uruguay)"
emoji = "ğŸ‡ºğŸ‡¾"

[[emoji]]
match = "(Vietnam|è¶Šå—)"
emoji = "ğŸ‡»ğŸ‡³"

[[emoji]]
match = "(Africa|å—é)"
emoji = "ğŸ‡¿ğŸ‡¦"

[[emoji]]
match = "(Ukraine|UA|ä¹Œå…‹å…°)"
emoji = "ğŸ‡ºğŸ‡¦"

[[emoji]]
match = "(Puerto.*?Rico|æ³¢å¤šé»å„)"
emoji = "ğŸ‡µğŸ‡·"

[[emoji]]
match = "(Ecuador|å„ç“œå¤šå°”)"
emoji = "ğŸ‡ªğŸ‡¨"

[[emoji]]
match = "(Venezuela|å§”å†…ç‘æ‹‰)"
emoji = "ğŸ‡»ğŸ‡ª"

[[emoji]]
match = "(Morocco|æ‘©æ´›å“¥)"
emoji = "ğŸ‡²ğŸ‡¦"

[[emoji]]
match = "(Nigeria|å°¼æ—¥åˆ©äºš)"
emoji = "ğŸ‡³ğŸ‡¬"

[[emoji]]
match = "(Nepal|å°¼æ³Šå°”)"
emoji = "ğŸ‡³ğŸ‡µ"

[[emoji]]
match = "(Bengal|å­ŸåŠ æ‹‰)"
emoji = "ğŸ‡§ğŸ‡©"

[[emoji]]
match = "(?i:\\bC[H]?N\\b|China|back|å›å›½|ä¸­å›½[^\\-]|æ±Ÿè‹[^\\-]|åŒ—äº¬[^\\-]|ä¸Šæµ·[^\\-]|å¹¿å·[^\\-]|æ·±åœ³[^\\-]|æ­å·[^\\-]|å¸¸å·[^\\-]|å¾å·[^\\-]|é’å²›[^\\-]|å®æ³¢[^\\-]|é•‡æ±Ÿ[^\\-]|æˆéƒ½[^\\-]|æ²³åŒ—[^\\-]|å±±è¥¿[^\\-]|è¾½å®[^\\-]|å‰æ—[^\\-]|é»‘é¾™æ±Ÿ[^\\-]|æ±Ÿè‹[^\\-]|æµ™æ±Ÿ[^\\-]|å®‰å¾½[^\\-]|ç¦å»º[^\\-]|æ±Ÿè¥¿[^\\-]|å±±ä¸œ[^\\-]|æ²³å—[^\\-]|æ¹–åŒ—[^\\-]|æ¹–å—[^\\-]|å¹¿ä¸œ[^\\-]|æµ·å—[^\\-]|å››å·[^\\-]|è´µå·[^\\-]|äº‘å—[^\\-]|é™•è¥¿[^\\-]|ç”˜è‚ƒ[^\\-]|é’æµ·[^\\-]|å†…è’™å¤[^\\-]|å¹¿è¥¿[^\\-]|è¥¿è—[^\\-]|å®å¤[^\\-]|æ–°ç–†[^\\-])"
emoji = "ğŸ‡¨ğŸ‡³"
